export  const RecipeData = [
        {
            id:1,
           
            title: 'Big and Juicy Wagyu Beef Cheeseburger',
            img: 'images/recipes/food-13.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Meat",
            profile: "./images/categories/meat.png",
          
        },
        {
            id:2,
           
            title: 'Fresh Lime Roasted Salmon with Ginger Sauce',
            img: 'images/recipes/food-14.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
             category: "Meat",
            profile: "./images/categories/meat.png",

        },
        {    
            id:3,
          
            title: 'Strawberry Oatmeal Pancake with Honey Syrup',
            img: 'images/recipes/food-15.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
        {
            id:4,
           
            title: 'Fresh and Healthy Mixed Mayonnaise Salad',
            img: 'images/recipes/food-16.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"anna wentern",
            category: "Vegan",
            profile: "./images/categories/vegan.png",
        },
        {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
        {
            id:6,
            
            title: 'Don’t forget to eat healthy food',
             img: 'images/recipes/food-20.png',
            date: "September 19",
            name:"wade wentern",
            Meal: 'dinner',
            time: '60 Minutes',
            category: "Meat",
            profile: "./images/categories/meat.png",
            
        },

        {
            id:7,
           
            title: 'Strawberry Oatmeal Pancake with Honey Syrup',
            img: 'images/recipes/food-18.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Meat",
            profile: "./images/categories/meat.png",
        },
        {
            id:8,
            
            title: 'Strawberry Oatmeal Pancake with Honey Syrup',
            img: 'images/recipes/food-19.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Vegan",
            profile: "./images/categories/vegan.png",
        },
        {
            id:9,
            
            title: 'The Creamiest Creamy Chicken and Bacon Pasta',
            img: 'images/recipes/food-20.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Breakfast",
            profile: "./images/categories/breakfast.png",
        },
         {
            id:10,
            category: "product",
            title: 'The Creamiest Creamy Chicken and Bacon Pasta',
            img: 'images/recipes/food-20.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Breakfast",
            profile: "./images/categories/breakfast.png",
        },
         {
            id:11,
            category: "product",
            title: 'The Creamiest Creamy Chicken and Bacon Pasta',
            img: 'images/recipes/food-20.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Breakfast",
            profile: "./images/categories/breakfast.png",
        },
         {
            id:12,
            category: "product",
            title: 'The Creamiest Creamy Chicken and Bacon Pasta',
            img: 'images/recipes/food-20.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Breakfast",
            profile: "./images/categories/breakfast.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
         {
            id:5,
            
            title: 'Chicken Meatballs with Cream Cheese',
            img: 'images/recipes/food-17.png',
            Meal: 'Breakfast',
            time: '30 Minutes',
            liked: false,
            date: "September 19",
            name:"wade wentern",
            category: "Dessert",
            profile: "./images/categories/dessert.png",
        },
    ]
